services:
  backend:
    build:
      context: ./backend
    pull_policy: build
    environment:
      - FILE_STORAGE=/app/uploads #DO NOT CHANGE, MODIFY THE BINDS
      - DB_PATH=/app/data/data.db #DO NOT CHANGE, MODIFY THE BINDS
      - WEBUI_URL=${APP_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ${UPLOAD_PATH}:/app/uploads
      - ${DATA_PATH}:/app/data
    restart: always
  frontend:
    build:
      context: ./frontend
    environment:
      - TERA_API_URL=${API_URL}
      - TERA_APP_URL=${APP_URL}
    pull_policy: build
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "${APP_PORT}:5173"
    depends_on:
      - backend
    restart: always
volumes:
  node_modules:
